.TH GRID-UPDATES 1 "December 2011" "User Commands"
.SH NAME
.PP
grid-updates - Helper Script for Tahoe-LAFS Nodes
.SH SYNOPSIS
.PP
\f[B]grid-updates\f[] [\f[I]OPTIONS\f[]] \f[I]ACTION\f[]
.SH DESCRIPTION
.PP
\f[I]grid-updates\f[] is a script intended to help keep Tahoe-LAFS
nodes' configurations up-to-date.
It can retrieve updated lists of introducers as well as simple news
updates.
.SH ACTIONS
.TP
.B -m, --merge-introducers
Merge your node's local introducers list with the subscription's.
.RS
.RE
.TP
.B -r, --replace-introducers
Replace your node's local list of introducers with the master list.
.RS
.RE
.TP
.B -n, --download-news
Retrieve news.
These will be stored in [node directory] and new contents will be
printed to stdout.
If you run this script as a cron job, the news will be emailed to
you.
Furthermore, an HTML version is placed into the node's web server's
\f[I]/static\f[] directory.
.RS
.RE
.TP
.B --check-version
Check for a new version of this script on the grid.
.RS
.RE
.TP
.B --download-update \f[I][target_directory]\f[]
Download a new version of this script from the grid to the
specified directory (implies \f[B]--check-update\f[]).
.RS
.RE
.TP
.B -R, --repair-subscriptions
Maintain or repair the health of the subscription service's URIs.
.RS
.RE
.SH OPTIONS
.TP
.B -c \f[I]config file\f[], --config \f[I]config file\f[]
Specify a grid-updates config file.
See \f[B]CONFIG\ FILES\f[] section below.
.RS
.RE
.TP
.B -d \f[I]directory\f[], --node-directory \f[I]directory\f[]
Specify the node directory (default: \f[I]~/.tahoe\f[]),
.RS
.RE
.TP
.B --list-uri \f[I]URI\f[]
Override the default location of the introducers list.
.RS
.RE
.TP
.B --news-uri \f[I]URI\f[]
Override the default location of the NEWS.tgz file.
.RS
.RE
.TP
.B --script-uri \f[I]URI\f[]
Override the default location of script updates.
.RS
.RE
.TP
.B --no-proxy
Disable proxy when downloading from non-tahoe URIs
.RS
.RE
.TP
.B -v, --verbose
Display more verbose output.
.RS
.RE
.TP
.B -V, --version
Display version information.
.RS
.RE
.TP
.B -h, --help
Print usage information.
.RS
.RE
.SH CONFIG FILES
.PP
\f[I]grid-updates\f[] will look for configuration files in
$XDG_CONFIG_HOME and $XDG_CONFIG_DIRS.
.PP
Accepted options are:
.TP
.B LISTURI = \f[I]URI\f[]
Same as --list-uri option above
.RS
.RE
.TP
.B NEWSURI = \f[I]URI\f[]
Same as --news-uri option above
.RS
.RE
.TP
.B SCRIPTURI = \f[I]URI\f[]
Same as --script-uri option above
.RS
.RE
.TP
.B HTTP_PROXY = \f[I]address\f[]
(The default is 127.0.0.1:4444)
.RS
.RE
.TP
.B NO_PROXY = \f[I]yes\f[]/\f[I]no\f[]
Same as --no-proxy option above.
.RS
.RE
.SH NOTES
.PP
\f[I]URIs\f[], in this context, can be either Tahoe-LAFS
directories
like
.PD 0
.P
.PD
\f[B]URI:DIR2-RO:22s6zidugdxaeikq6lakbxbcci:mgrc3nfnygslyqrh7hds22usp6hbn3pulg5bu2puv6y3wpoaaqqq\f[]
.PD 0
.P
.PD
or
regular FQDNs like \f[B]http://example.i2p/\f[] or
\f[B]http://www.example.com/\f[].
.SH ERRORS
.PP
If the script repeatedly fails to retrieve a file from the grid,
the share may be damaged.
Run \f[B]--repair-subscriptions\f[] which will attempt to
deep-check the share.
.PP
If that doesn't help, you will most likely have to find new URIs to
subscribe to.
.PP
Use \f[B]--check-version\f[] to see if there is a new version of
\f[I]grid-updates\f[] available, which may already include new
default URIs.
.PP
Finally, you can check on IRC, mailing lists and Wikis for updated
information.
.SH FILES
.PP
\f[I]~/.tahoe/NEWS\f[]
.PD 0
.P
.PD
\f[I]~/.tahoe/public_html/NEWS.html\f[]
.PD 0
.P
.PD
\f[I]~/.tahoe/introducers\f[]
.PD 0
.P
.PD
\f[I]$XDG_CONFIG_HOME/grid-updates/config\f[]
(most commonly
~/.config)
.PD 0
.P
.PD
\f[I]$XDG_CONFIG_DIRS/grid-updates/config\f[]
(most commonly /etc/xdg)
.SH BUGS
.PP
Please report bugs in #tahoe-lafs on Irc2p or via email (see
below).
.SH SEE ALSO
.PP
The \f[I]grid-updates\f[] git repository:
http://git.repo.i2p/w/grid-updates.git
.PP
The README on the grid:
.PP
\f[CR]
      URI:DIR2-RO:mjozenx3522pxtqyruekcx7mh4:eaqgy2gfsb73wb4f4z2csbjyoh7imwxn22g4qi332dgcvfyzg73a/README.html
\f[]
.PP
Information about Tahoe-LAFS for I2P and the I2P grid:
http://killyourtv.i2p
.SH LICENSE
.PP
\f[I]grid-updates\f[] has been released into the public domain.
This means that you can do whatever you please with it.
.SH AUTHORS
darrob <darrob@mail.i2p>, killyourtv <kytv@mail.i2p>.

