#!/usr/bin/env python

import sys
if sys.hexversion < int(0x020600f0):
    sys.stderr.write('ERROR: %s requires Python 2.6 or newer.\n' % sys.argv[0])
    sys.exit(1)

from gridupdates import grid_updates
try:
    grid_updates.main()
except KeyboardInterrupt:
    print("\ngrid-updates interrupted by user.")
    sys.exit(1)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
