#!/usr/bin/env python

import sys
if sys.hexversion < int(0x020600f0):
    sys.stderr.write('ERROR: %s requires Python 2.6 or newer.\n' % sys.argv[0])
    sys.exit(1)

import gridupdates
gridupdates.main()


# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
